#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")
ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

for FILE in $STAGED_FILES
do
  git show ":$FILE" | $ESLINT --stdin --stdin-filename "$FILE"

  if [[ "$?" == 0 ]]; then
    printf "\033[32mESLint Passed: $FILE\033[0m"
  else
    printf "\033[41mESLint Failed: $FILE\033[0m"
    PASS=false
  fi

  printf "\n"
done

if ! $PASS; then
  printf "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
else
  printf "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

printf "\n"

$PASS
exit $?